### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by VinayakTekade** [aravindvnair99/AYKYA-Fest#10]
## Requirements to be fulfilled 
- [x] Hamburger without navbar
- [x] Countdown for logo reveal
- [x] Logo reveal on countdown

### Stage 2
- [x] Timer Syle 
- [x] Test with Logo
- [x] Stars Animation
- [x] Test Background and font colors

**Comment by VinayakTekade** [comment]
Stage 2 is yet to complete.

**Comment by Subaharish** [comment]
> Stage 2 is yet to be completed.

@VinayakTekade Completed
