### ISSUE TITLE
additional info to be added for the event - art gallery

### ISSUE THREAD

**Issue by pvignesh53** [aravindvnair99/AYKYA-Fest#110]
Art gallery - cultural wing event

Info to be added - 

Themes for the gallery:

1. Mental health
2. Effect of covid on society
3. Your dream come true

**Comment by aravindvnair99** [comment]
@suneel87 Can you take this up?

**Comment by suneel87** [comment]
> @suneel87 Can you take this up?

@aravindvnair99 Yeah, sure.I'll assign myself
