### ISSUE TITLE
Payment Integration

### ISSUE THREAD

**Issue by VinayakTekade** [aravindvnair99/AYKYA-Fest#16]
## Requirements to be fulfilled

- [x] Setup Townscript
- [x] A modal with Townscript
- [x] Event registration
- [x] Redirect to payment gateway

**Comment by aravindvnair99** [comment]
@suneel87 Townscript account is created. AYKYA team will add events soon. For the time being, use [SLAC 2019 Townscript code](https://github.com/aravindvnair99/SLAC-2019/blob/f93eb1a9c1b736fb799b6c82abc6a6d290635c84/functions/views/index.ejs#L568-L580) to get an estimate of the layout.

**Comment by aravindvnair99** [comment]
Fixed in 86f701e5471b3a038981fc3da4227fc590190977 0930c828f20b0b4c894bc6f051b132d3b56d8eea
