### ISSUE TITLE
Major Fixes and Optimizations in Frontend

### ISSUE THREAD

**Issue by VinayakTekade** [aravindvnair99/AYKYA-Fest#46]
## Requirements to be fulfilled
- [x] Minor CSS fixes in all the page
- [x] Add Schedule
- [x] Remove Scrollbar in nav
- [x] Update links in Nav
- [x] Update Landing page for fest
- [x] Check Screen responsiveness
- [x] Text formatting in Schedule Page
- [x] Collapse on About Aykya page
- [x] Update favicon
- [x] Logo at the top corner of every page inside the main menu shows an error
- [x] In the schedule section, 'day 1' 'day 2' etc aren't aligned to the centre of the box
- [x] In the management Week section of past events, there's no need for a 'next event' button
- [x] Designations for the organizing team page - doesn't make sense to have 3 "team heads"
- [x] **Add to Schedule** Workshop on Technical and Management students by TEM IEEE CHAPTER - Sunday 10 to 1AM
- [x] In the "Contact Us" page, when you hover over Contact Us, it gets blackened
- [x] Looks better when the aykya logo is in the centre (at the top) of every page, as of now it looks like it is a bit to the left. 'buy tickets' button could either be a bit smaller or the words could come one below the other.
- [x] If i click on get tickets at bottom. It doesn't go to ACRD page.
- [x] Have to change the Campus Ambassador text (For mobile view). 
- [x] Remove unnecessary HTML

## Pending
- [ ] Refactor code
- [ ] Remove unnecessary CSS
- [ ] Remove unnecessary JS
- [ ] Check console for malfunctioning JS and rectify
- [ ] Remove unnecessary images

# Feel free to add to this list if you discover any bugs

**Comment by suneel87** [comment]
I'll be taking up: 
1)In the management Week section of past events, there's no need for a 'next event' button
2)n the schedule section, 'day 1' 'day 2' etc aren't aligned to the centre of the box
3)Buy tickets option does nothing(Should I just remove this/Hide it?)

**Comment by aravindvnair99** [comment]
> I'll be taking up:
> 1)In the management Week section of past events, there's no need for a 'next event' button

@suneel87 For everything listed here, make it into a separate issue and close that instead of this. You can assign yourself one at a time.

@PriyaaIyer @Subaharish @VinayakTekade You 3 can also follow the same.

**Comment by VinayakTekade** [comment]
[Bug report](https://docs.google.com/document/d/1EsM_HB-6n0s5Sdb3zZhwkq_jlTNdLIVaewNC80S-1lY/edit)
