### ISSUE TITLE
Resize members page images

### ISSUE THREAD

**Issue by aravindvnair99** [aravindvnair99/AYKYA-Fest#57]
Need to fix:

- [ ] Images aren't aligned properly, especially on mobile devices
- [ ] Images are of different resolutions, should be made uniform
- [x] Images need to be resized and compressed for web quality, HD+ resolutions not required

**Comment by suneel87** [comment]
@aravindvnair99 Regarding the alignment issue, right now the images are placed according to the original template and they seem to be responding fine to different device widths. Maybe, check them out using these tools:
1.Am I Responsive: http://ami.responsivedesign.is/#
2.isResponsive: http://www.isresponsive.com/ViewOnDevice
3.Responsive Design Testing: http://mattkersley.com/responsive/
4.Responsinator: http://www.responsinator.com/
5.Designmodo: https://designmodo.com/responsive-test/

Link to test with: https://aykyamultifest.com/members (or) aykyamultifest.com/members

**Note:** CSS effect and responsiveness for devices having pixel width of 320px and below can be ignored as it is highly unlikely for people to be using phones/devices with those specifications. All sizes above 320px width are responding fine.

**Comment by suneel87** [comment]
Oh, by alignment you mean, the shapes of the images? Then, should I just resize all images to one size?

**Comment by aravindvnair99** [comment]
> Oh, by alignment you mean, the shapes of the images? Then, should I just resize all images to one size?

@suneel87 Yep, one size might look odd considering it's more of an up-down layout. We need to keep them uniform is what I meant. All the ones on left in one size and right in one size. Experiment and see how it goes. Previously when the count was odd, I created the issue. Right now, after I added myself, the count is even now. So, it's looking better, but still not right. Try Ctrl + Shift + I and then Ctrl + Shift + M and switch to Pixel for example. You'll notice what I'm talking about.

**Comment by suneel87** [comment]
> > Oh, by alignment you mean, the shapes of the images? Then, should I just resize all images to one size?
> 
> @suneel87 Yep, one size might look odd considering it's more of an up-down layout. We need to keep them uniform is what I meant. All the ones on left in one size and right in one size. Experiment and see how it goes. Previously when the count was odd, I created the issue. Right now, after I added myself, the count is even now. So, it's looking better, but still not right. Try Ctrl + Shift + I and then Ctrl + Shift + M and switch to Pixel 2 XL for example. You'll notice what I'm talking about.

@aravindvnair99 Thanks for the clarification, I'll check it out and see what I can do. But the responsiveness for my page is fine, no?

**Comment by aravindvnair99** [comment]
> > > Oh, by alignment you mean, the shapes of the images? Then, should I just resize all images to one size?
> > 
> > 
> > @suneel87 Yep, one size might look odd considering it's more of an up-down layout. We need to keep them uniform is what I meant. All the ones on left in one size and right in one size. Experiment and see how it goes. Previously when the count was odd, I created the issue. Right now, after I added myself, the count is even now. So, it's looking better, but still not right. Try Ctrl + Shift + I and then Ctrl + Shift + M and switch to Pixel 2 XL for example. You'll notice what I'm talking about.
> 
> @aravindvnair99 Thanks for the clarification, I'll check it out and see what I can do. But the responsiveness for my page is fine, no?

@suneel87 Responsiveness is fine. Just that the image resolutions need to be fixed to make it look better. Try putting all as same resolution and check how it looks. Else keep the left side in one and right side in another to create that up-down effect. Shall I assign this issue to you?
