### ISSUE TITLE
Redirection to SLAC website for SLAC 2020 registration

### ISSUE THREAD

**Issue by newb-dev-1008** [aravindvnair99/AYKYA-Fest#71]
Under the sub-part of the website dealing with the registration for SLAC, please ensure the link redirects to the registration page of SLAC 2020 (https://slac.faceaseb.com/#pricing).
Also, please ensure you enter the following details for registration:
1. Teams of 3 or 4 allowed only.
2. Individual participation is allowed, but will not be eligible for prizes and judgements.

**Comment by aravindvnair99** [comment]
> Under the sub-part of the website dealing with the registration for SLAC, please ensure the link redirects to the registration page of SLAC 2020 (https://slac.faceaseb.com/#pricing).
> Also, please ensure you enter the following details for registration:
> 
> 1. Teams of 3 or 4 allowed only.
> 2. Individual participation is allowed, but will not be eligible for prizes and judgements.

@newb-dev-1008 Why not send to `https://slac.faceaseb.com` for the whole of SLAC? They can view all the details there and register. A small writeup and poster on the AYKYA website should do the job I feel.

**Comment by newb-dev-1008** [comment]
@aravindvnair99 that would be ideal. I thought Aykya wanted to keep a tab on registrations, so I suggested that; but what you've suggested should be fine- that is what I intended in the first place. Just include a button (or anything that will redirect the user to https://slac.faceaseb.com.)

**Comment by aravindvnair99** [comment]
> @aravindvnair99 that would be ideal. I thought Aykya wanted to keep a tab on registrations, so I suggested that; but what you've suggested should be fine- that is what I intended in the first place. Just include a button (or anything that will redirect the user to https://slac.faceaseb.com.)
> 
> > <img alt="" width="48" src="/mstile-150x150.png">**[SLAC 2020](https://slacfest.in)**Stay Late and Code

@newb-dev-1008 AYKYA team can keep track of registrations. You just need to inform them the count and details. Else, participants will end up filling two forms if we were to go with https://github.com/aravindvnair99/AYKYA-Fest/issues/71#issue-723292364

**Comment by newb-dev-1008** [comment]
@aravindvnair99 yeah alright, we'll just redirect the entire thing to SLAC the way you were suggesting. A small writeup and poster on Aykya should suffice; just ensure that the users who're willing to register for SLAC are able to click and direct themselves to the SLAC website for the registration process.

**Comment by VinayakTekade** [comment]
@newb-dev-1008 We have linked slac.faceaseb.com in our schedule page in #73

**Comment by Ashwin-Ganti** [comment]
@newb-dev-1008 We have linked the Slac website in our shedule page #73

**Comment by newb-dev-1008** [comment]
I won't be able to see the page until it gets deployed, but as long as its linked, its peaceful. Thanks a ton! @VinayakTekade @Ashwin-Ganti
